version: '3.8'

services:
  postgres:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - store_data:/var/lib/postgresql/data
  store_server:

volumes:
  store_data:
